#!/bin/bash

apt-get update
apt-get upgrade

apt-get install build-essential autoconf
apt-get install linux-headers-$(uname -r)

apt-get install curl xsel tree

# Source control
apt-get install mercurial bzr git subversion

# Vim
apt-get install vim
apt-get install vim-gnome

apt-get install libssl-dev openssl
apt-get install libncurses5-dev libncurses5


