#!/bin/bash

add-apt-repository ppa:langdalepl/gvfs-mtp
add-apt-repository ppa:ubuntu-sdk-team/ppa
add-apt-repository ppa:webupd8team/sublime-text-3

# mongodb
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | tee /etc/apt/sources.list.d/mongodb.list

apt-get update
apt-get upgrade

apt-get install zsh 

# Ubuntu stuff
apt-get dist-upgrade

apt-get install build-essential autoconf
apt-get install ubuntu-sdk

apt-get install linux-headers-$(uname -r) 

# Other tools and libraries I know I'll need
apt-get install curl xsel sqlite tree
apt-get install unetbootin gparted

apt-get install postgresql-client-common # this first
apt-get install postgresql-client postgresql postgresql-contrib pgadmin3

apt-get install mongodb-org

# Source control
apt-get install mercurial bzr git subversion

# Vim
apt-get install vim
apt-get install vim-gnome

# Virtualbox
apt-get install virtualbox

# LAMP
apt-get install apache2
apt-get install apache2-bin

# Python stuff
apt-get install libmysqlclient-dev
apt-get install libbz2-dev libgdbm-dev liblzma-dev libreadline6-dev
apt-get install libpq-dev
apt-get install libxml2-dev libxslt1-dev python-dev
apt-get install python python-tk idle python-pmw python-imaging
apt-get install libssl-dev openssl
apt-get install sqlite3 libsqlite3-dev
apt-get install libncurses5-dev libncurses5
apt-get install python-setuptools
apt-get install python-pip virtualenv virtualenvwrapper
apt-get install python3-pip
apt-get install bpython

apt-get install libsdl1.2-dev libsmpeg-dev libasound2-doc libglib2.0-doc # for pygame
apt-get install libsdl-ttf2.0-dev libsdl-image1.2-dev libsdl-mixer1.2-dev # pygame
apt-get install libportmidi-dev libavformat-dev libswscale-dev libv4l-dev # pygame

# Mono
apt-get install libglib3.0-cil-dev libglib3.0-cil
apt-get install mono-complete
apt-get install monodevelop glade
# apt-get install libtool libgnome2.0-cil-dev libgnome2.24-cil gnome-sharp2 libmono-addins-cil-dev libmono-addins-gui-cil-dev libvala-0.22-0 libvala-0.22-dev libvala-0.22-0-dbg libglib2.0

# Haskell
apt-get install haskell-platform

# Ruby
apt-get install ruby-dev
\curl -sSL https://get.rvm.io | bash -s stable
apt-get install jekyll

# Node stuff
# TODO add node
npm install -g grunt-cli
npm install -g browserify
npm install -g topojson
npm install -g less
npm install -g watch-less

# Java!
apt-get install openjdk-7-jre openjdk-7-jdk eclipse scala

# Mount my android device
apt-get install gvfs

# Other apps
apt-get install inkscape blender aseprite audacity
apt-get install sublime-text-installer

# mp3
apt-get install gstreamer1.0-plugins-ugly

apt-get install qgis python-qgis qgis-plugin-grass

apt-get install python-sphinx
apt-get install texlive-latex-base
apt-get install texlive-latex-base
apt-get install tor

#chsh -s `which zsh`

reboot

